Add controllers
cayoskoro/java-shareit pull request #1
Opened 2023-12-24 22:38 UTC by cayoskoro

- Созданы модели User, Item;
- Созданы контроллеры UserController, ItemController;
- Реализованы кастомные исключения;
- Создан обработчик ошибок;
- Созданы сервисные слои UserService, ItemService и их реализации;
- Созданы репозитории UserRepository, ItemRepository и их реализации;
- Созданы UserDto, ItemDto;
- Созданы ограничения для вариации валидации UserDto в зависимости от эндпонитов.

2023-12-25 16:10 UTC, Fleaman777 requested changes

2023-12-25 16:10 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto getItemById(@RequestHeader("X-Sharer-User-Id") long userId, @PathVariable long itemId) {
X-Sharer-User-Id - можно вынести в константу

2023-12-25 16:10 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private final ItemMapper mapper;
на этот счет как-будто нет какого-то общего мнения, но я предпочитаю маппинг выполнять в методах сервиса, а в контроллере оставлять только зависимость на сервис, а он уже в свое очередь будет иметь зависимость на все, что необходимо, 

так у нас получается более четкое разделение логики

2023-12-25 16:10 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        } else if (!Pattern.matches("^[\\sа-яА-Яa-zA-Z0-9]+$", text)) {
соответственно эта валидация так же должна быть либо в сервисе, либо в отдельном валидаторе 

и хорошо бы Паттерн вынести в константу, с подходящим названием, что бы лучше им управлять

2023-12-25 16:10 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/user/repository/impl/UserRepositoryImpl.java
> +    private long generateId() {
хорошая идея вынести generateId в отдельный метод

2023-12-25 16:10 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/user/repository/impl/UserRepositoryImpl.java
> +        }
подход к проверке наличия электронной почты в методе create репозитория понятен, но есть пара моментов для улучшения. 

Лучше разделить логику проверки и создания пользователя. Проверку на уникальность электронной почты целесообразнее выполнять на уровне сервиса, а не репозитория. Репозиторий должен заниматься только взаимодействием с хранилищем данных. Это поможет сделать код более чистым, модульным и легче для тестирования. В идеале, метод create должен только создавать нового пользователя, не занимаясь проверками бизнес-логики. Также, это повысит переиспользуемость и читаемость кода.

аналогично в др похожих местах

2023-12-26 23:55 UTC, cayoskoro commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private final ItemMapper mapper;
Сделал, но получается, что в методах контроллеров происходит только return бизнес логики, а в самом сервисном слое появляется больше кода. Разве в контроллерах совсем ограничивается запросом сервисной логики и обработкой заголовков? Просто хочу понять нормально ли это, так как действительно вижу, что подход у каждого и каждой команды разный.

2023-12-26 23:57 UTC, cayoskoro commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        } else if (!Pattern.matches("^[\\sа-яА-Яa-zA-Z0-9]+$", text)) {
Создал отдельный класс Constants с паттерном "^[\\sа-яА-Яa-zA-Z0-9]+$"

2023-12-27 19:22 UTC, Fleaman777 approved these changes

2023-12-27 23:02 UTC, merged